CREATE database grocery_db;
USE grocery_db;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
SELECT * FROM supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

SELECT * FROM categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

SELECT * FROM employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

SELECT * FROM customers;
-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT, 
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM orders;



-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM order_details;

-- Analysis Questions
-- 1️. Customer Insights
-- How many unique customers have placed orders?

SELECT  COUNT(DISTINCT C.cust_id) AS unique_customers
FROM Customers as C
JOIN orders as O
on C.cust_id = O.cust_id;

-- Which customers have placed the highest number of orders?
SELECT O.cust_id , cust_name, count(O.cust_id) FROM customers AS C
JOIN orders AS O
on C.cust_id = O.cust_id
group by O.cust_id
ORDER BY count(O.cust_id) DESC;   

-- What is the total and average purchase value per customer?

SELECT C.cust_id,C.cust_name,sum(o_d.total_price) as total_price, 
avg(o_d.total_price) as avg_price 
FROM customers as C
JOIN orders as O
on C.cust_id = O.cust_id
JOIN order_details as o_d
on O.ord_id = o_d.ord_id 
group by  C.cust_id, C.cust_name
ORDER BY C.cust_id asc;  

-- Who are the top 5 customers by total purchase amount?
SELECT C.cust_id, C.cust_name, sum(o_d.total_price) as total 
FROM customers AS C
JOIN orders AS O
ON C.cust_id = O.cust_id
JOIN order_details AS o_d
ON O.ord_id = o_d.ord_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total DESC
LIMIT 5;




-- 2. Product Performance

-- How many products exist in each category?
SELECT C.cat_id, C.cat_name , count(P.cat_id) AS total_products
FROM categories AS C
JOIN products AS P
ON C.cat_id = P.cat_id
group by C.cat_id, cat_name;


-- What is the average price of products by category?

SELECT C.cat_id, C.cat_name , avg(P.price) AS avg_price
FROM categories AS C
JOIN products AS P
ON C.cat_id = P.cat_id
group by C.cat_id, C.cat_name;

-- Which products have the highest total sales volume (by quantity)?
SELECT P.prod_id,P.prod_name, sum(o_d.quantity) AS volume
FROM products AS P
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
GROUP BY P.prod_id,P.prod_name
ORDER BY volume DESC; 


-- What is the total revenue generated by each product?
SELECT P.prod_id, P.prod_name, sum(o_d.quantity*o_d.each_price) AS total_revenue
FROM products AS P
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
GROUP BY P.prod_id, P.prod_name;


-- How do product sales vary by category and supplier?
SELECT C.cat_name , S.sup_name, sum(o_d.total_price) AS total_sales
FROM categories AS C
JOIN products AS P
ON C.cat_id = P.cat_id
JOIN supplier AS S
ON P.sup_id = S.sup_id
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
GROUP BY C.cat_name, S.sup_name;

-- 3. Sales and Order Trends
-- How many orders have been placed in total?
SELECT count(*) AS total_orders
FROM orders;

-- What is the average value per order?
with order_values as (
    select o.ord_id, sum(o_d.total_price) as order_total
    from orders o
    join order_details o_d
    on o.ord_id = o_d.ord_id
    group by o.ord_id
)
select avg(order_total) as avg_order_value
from order_values;

SELECT AVG(total) FROM
(SELECT ord_id, sum(total_price) AS total
FROM order_details AS O
GROUP BY ord_id) AS new;

 

-- On which dates were the most orders placed?
SELECT order_date, COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;   



-- What are the monthly trends in order volume and revenue?
SELECT 
    DATE_FORMAT(STR_TO_DATE(O.order_date, '%m/%d/%Y'), '%Y-%m') AS order_month,
    COUNT(DISTINCT O.ord_id) AS total_orders,
    SUM(o_d.total_price) AS total_revenue
FROM orders AS O
JOIN order_details AS o_d
ON O.ord_id = o_d.ord_id
GROUP BY DATE_FORMAT(STR_TO_DATE(O.order_date, '%m/%d/%Y'), '%Y-%m')
ORDER BY order_month;


-- How do order patterns vary across weekdays and weekends?

SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(O.order_date, '%m/%d/%Y')) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT O.ord_id) AS total_orders,
    SUM(o_d.total_price) AS total_revenue
FROM orders O
JOIN order_details o_d
ON O.ord_id = o_d.ord_id
GROUP BY day_type;


-- 4️. Supplier Contribution
-- How many suppliers are there in the database?
SELECT COUNT(*) FROM supplier;

-- Which supplier provides the most products?
SELECT S.sup_id ,S.sup_name, COUNT(P.prod_id) AS total_products
FROM supplier AS S
JOIN products AS P
ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name
ORDER BY total_products DESC
LIMIT 1;



-- What is the average price of products from each supplier?
SELECT S.sup_id, S.sup_name, AVG(P.price) AS average_price
FROM supplier AS S
JOIN products AS P
ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name ;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT S.sup_id, S.sup_name, sum(total_price) AS total_revenue
FROM supplier AS S
JOIN products AS P
ON S.sup_id = P.sup_id
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
GROUP BY S.sup_id, S.sup_name
ORDER BY total_revenue DESC;

-- 5. Employee Performance
-- How many employees have processed orders?
SELECT COUNT(DISTINCT O.emp_id) AS total_employees
FROM orders AS O;



-- Which employees have handled the most orders?
SELECT E.emp_id , E.emp_name, COUNT(O.ord_id) AS total_orders
FROM employees AS E
JOIN orders AS O
ON E.emp_id = O.emp_id
GROUP BY E.emp_id, E.emp_name 
ORDER BY total_orders DESC;


-- What is the total sales value processed by each employee?
SELECT E.emp_id, E.emp_name, SUM(o_d.total_price) AS total_sales
FROM employees AS E
JOIN orders AS O
ON E.emp_id = O.emp_id
JOIN order_details AS o_d
ON O.ord_id = o_d.ord_id
GROUP BY E.emp_id, E.emp_name
ORDER BY total_sales DESC; 


-- What is the average order value handled per employee?
SELECT E.emp_id, E.emp_name, AVG(o_d.total_price) AS avg_value
FROM employees AS E
JOIN orders AS O
ON E.emp_id = O.emp_id
JOIN order_details AS o_d
ON O.ord_id = o_d.ord_id
GROUP BY E.emp_id, E.emp_name;

-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
SELECT quantity,AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;

-- What is the average quantity ordered per product?
SELECT P.prod_id, P.prod_name, avg(o_d.quantity) AS average_quantity
FROM products AS P
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
GROUP BY P.prod_id, P.prod_name; 


-- How does the unit price vary across products and orders?
SELECT 
    P.prod_id,
    P.prod_name,
    o_d.ord_id,
    o_d.each_price
FROM products AS P
JOIN order_details AS o_d
ON P.prod_id = o_d.prod_id
ORDER BY P.prod_id, o_d.ord_id;














